### ISSUE TITLE
Clarify each component under Falco organization.

### ISSUE THREAD

**Issue by aijamalnk** [falcosecurity/falco-website#1004]
/area documentation

**What would you like to be added**:
Describe the specifics of what a component does on its repo and link back to how it works within the Falco construct (shipped with, plugin, enhancement, etc)

For each repo in GH, be very clear on what repo holds and its purpose. If there are multiple components on a single repo, add a clear definition for each one, and how it maps back to falco concepts.

Add cross-references.

**Why is this needed**:
To improve experience for someone navigating through Falco project.

**Comment by leogr** [comment]
This may be related to https://github.com/falcosecurity/evolution/issues/271

**Comment by LucaGuerra** [comment]
This is indeed related to https://github.com/falcosecurity/evolution/issues/271 . In order to make it easier for users to find the complete list, we added a link to evolution in the about page: https://github.com/falcosecurity/falco-website/pull/1048
