### ISSUE TITLE
Improve cross-referencing in Falco website and repositories

### ISSUE THREAD

**Issue by aijamalnk** [falcosecurity/falco-website#1005]
/area documentation

**What would you like to be added**:
Improve cross-references between all the repos, plugins, libraries, etc. to the main documentation site and main repo as well as the evolution repo.

**Why is this needed**:
For better user experience and understanding.

**Comment by LucaGuerra** [comment]
https://github.com/falcosecurity/falco-website/pull/1082 is related to this effort.

**Comment by leogr** [comment]
Cross-linking between evolution and other repos has been addressed by https://github.com/falcosecurity/evolution/issues/271.

Furthermore, the website contains several links to the evolution repository, for example, https://falco.org/docs/#what-are-the-ecosystem-projects-that-can-interact-with-falco.

**Comment by LucaGuerra** [comment]
I checked the website and I believe that every page that introduces an important component (Falco, Libraries, Plugins, Rules etc) is linked to the appropriate repository. Except maybe for one thing:
- [ ] Perhaps falcoctl could get more love in the main pages

What may be missing in a few cases is linking core repositories back to the documentation website
- [ ] Helm chart repository, Falco link and main docs website
- [ ] deploy-kubernetes, Falco link and main docs website
- [ ] falco-website double check
- [ ] falcoctl link to Falco, main docs website
- [ ] libs link to the main falco website and double check for outdated information

**Comment by leogr** [comment]
Done!
/close
