### ISSUE TITLE
Add a "how to guide" on writing, deploying and fine tuning rules

### ISSUE THREAD

**Issue by aijamalnk** [falcosecurity/falco-website#1008]
/area documentation

**What would you like to be added**:
Clear instructions that set expectations on customization and tuning of the ruleset. Provide examples and metaphors to make the concepts stick

**Why is this needed**:
Set expectations correctly on Falco usage.

**Comment by vjjmiras** [comment]
Already working on a documentation section to start writing rules from scratch.

**Comment by LucaGuerra** [comment]
I was able to talk with @vjjmiras about this. He is working on improving clarity about how to add custom rules. I will also work to improve documentation about how to tune noisy rules and deploy them and we're going to submit that to the website.

I think the "rules" section should be the right place as long as it's cross-referenced from other places that might point the user in the right direction when customizing their rules.

**Comment by leogr** [comment]
This has been addressed by https://github.com/falcosecurity/falco-website/pull/1077
/close
