### ISSUE TITLE
Add a contribution guides for Falco rules

### ISSUE THREAD

**Issue by aijamalnk** [falcosecurity/falco-website#1009]
/area documentation

**What would you like to be added**:
Define criteria for rules contribution. Clarify how rules can be contributed to, how are they modular, be clear about what kinds of rules will not be accepted, and ensure all rules have corresponding tests to make sure they work.

**Why is this needed**:
Users need a clear guide on contributing back and expanding Falco rules.

**Comment by leogr** [comment]
Depends on https://github.com/falcosecurity/rules/pull/76

**Comment by leogr** [comment]
@lg @incertum could you help with this? :pray:

**Comment by incertum** [comment]
Absolutely, here are some notes when Luca and I chatted last time. We will coordinate.

- [ ] Rules Style Guide -> website
- [ ] How to Share Your Falco Rules -> website
- [ ] Adopter Guide -> website
- [ ] Rules Maturity Definitions -> rules repo
- [ ] CONTRIBUTING -> enforce style guide and maturity framework, rules repo
- [ ] PR Template -> rules repo, featuring a quick checklist

**Comment by leogr** [comment]
> * [ ]  Rules Style Guide -> website
> * [ ]  How to Share Your Falco Rules -> website
  - @incertum are you working on these items? Do you need any help with that? Please let us know.
> * [ ]  Adopter Guide -> website
  - @LucaGuerra and @vjjmiras are working on this already
> * [ ]  Rules Maturity Definitions -> rules repo
  - @incertum I guess you're on top of this

> * [ ]  CONTRIBUTING -> enforce style guide and maturity framework, rules repo
> * [ ]  PR Template -> rules repo, featuring a quick checklist
  - for these two, we don't have an owner yet, let's coordinate

**Comment by incertum** [comment]
@leogr assignments sound good. Haven't started yet, but I can get PRs up quickly (everywhere you mentioned me) and then we have you, Luca and Vicente help and polish the content?

I believe the first 2 "Rules Style Guide" and "How to Share Your Falco Rules" will require most collab.

**Comment by leogr** [comment]
> * Rules Maturity Definitions -> rules repo
:point_right:  https://github.com/falcosecurity/rules/pull/118

**Comment by incertum** [comment]
Initial pass done, let's close this after we are done with a few touch up PRs as needed.

**Comment by leogr** [comment]
> Initial pass done, let's close this after we are done with a few touch up PRs as needed.

Ok, what's missing?

**Comment by leogr** [comment]
Last PR :point_right: https://github.com/falcosecurity/falco-website/pull/1094 merged!

/close
