### ISSUE TITLE
Get feedback from Falco users and Document their case study

### ISSUE THREAD

**Issue by aijamalnk** [falcosecurity/falco-website#1036]
**What would you like to be added**:
A direct feedback or case studies from existing Falco users. What challenges and benefits they had from adopting Falco?

**Why is this needed**:
Currently, there aren't many clear examples of Falco usage that we can reference. Documented feedback in the form of case studies helps to inform and guide potential adopters in understanding how Falco can be used and what needs it can address. It also sets clear expectations on whether Falco needs to be used within or alongside other projects and products to gain value from it. Understanding which tools, projects, and products are used by adopters (plug-ins and exporters serve as sources for some of this information) and describing them as integration capabilities will give potential adopters a complete picture.

- [x] Align with Taylor Dolezal on how to engage users and get their feedback.
- [x] Interview Falco adopters
- [x] Document case studies of Falco adopters. Include details on the architecture, value and results from adopting Falco.
- [x] Publish case studies on Falco.org
- [ ] Share the case studies with the CNCF community

**Comment by LucaGuerra** [comment]
@mikegcoleman can you type `/assign` so that the bot will assign you to this issue? Thanks!

**Comment by leogr** [comment]
> * Publish case studies on Falco.org

:point_right: https://github.com/falcosecurity/falco-website/pull/1089

**Comment by leogr** [comment]
This has been addressed by https://github.com/falcosecurity/falco-website/pull/1089
/close

@aijamalnk Could you open a different issue to track the only remaining item :point_down: ? :pray: 
> [ ] Share the case studies with the CNCF community
