### ISSUE TITLE
Missing "noindex, nofollow" tag on website snapshot

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco-website#1172]
**What happened**:

To avoid SEO issues, all archived versions of the website (i.e. https://v0-35.falco.org/) should include the following tag:
```
<meta name="robots" content="noindex, nofollow">
```

- As an example, K8s website does so :point_right: view-source:https://v1-26.docs.kubernetes.io/docs/home/
- We did so up to version 0.31 :point_right: view-source:https://v0-31.falco.org/
- From 0.32 we miss it :point_right: view-source:https://v0-32.falco.org/. **This must be fixed!** :slightly_smiling_face:

We likely broke it at some point when reviving the website.

**What you expected to happen**:

All website archived versions (ie. snapshots) must include `<meta name="robots" content="noindex, nofollow">`

**How to reproduce it (as minimally and precisely as possible)**:

Look at the source code of the HTML page of our archived snapshot.

**Comment by LucaGuerra** [comment]
We're still not sure if this fixed it :)

**Comment by vjjmiras** [comment]
> We're still not sure if this fixed it :)

Right, this affects several branches.

**Comment by LucaGuerra** [comment]
Adding the PRs that closed this issue:

https://github.com/falcosecurity/falco-website/pull/1185
https://github.com/falcosecurity/falco-website/pull/1184
https://github.com/falcosecurity/falco-website/pull/1183
https://github.com/falcosecurity/falco-website/pull/1186

```
$ for i in {26..35}; do echo $i; curl -s https://v0-$i.falco.org |sed -e 's,<,\n<,g'|grep -i name=robots ; done
26
<meta name=robots content="noindex, nofollow">
27
<meta name=ROBOTS content="NOINDEX, NOFOLLOW">
28
<meta name=ROBOTS content="NOINDEX, NOFOLLOW">
29
<meta name=ROBOTS content="NOINDEX, NOFOLLOW">
30
<meta name=ROBOTS content="NOINDEX, NOFOLLOW">
31
<meta name=ROBOTS content="NOINDEX, NOFOLLOW">
32
<meta name=robots content="noindex, nofollow">
33
<meta name=robots content="noindex, nofollow">
34
<meta name=robots content="noindex, nofollow">
35
<meta name=robots content="noindex, nofollow">
```

Done!
