### ISSUE TITLE
Improve rules onboarding docs based on community feedback

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco-website#1177]
Follow up item from https://github.com/falcosecurity/falco/issues/2791#issuecomment-1755606485 discussion.

CC @enote-kane

**Comment by incertum** [comment]
Here is another question https://github.com/falcosecurity/rules/issues/184 -> I think we could improve docs also in this regard.

**Comment by incertum** [comment]
Potentially also improve docs around enabling and disabling rules, e.g. see https://github.com/falcosecurity/falco/pull/2920#discussion_r1408564126. At the moment it is also unclear if we want to add enabling/disabling capabilities to falco.yaml in addition to having the cmd args as option? @leogr do you have additional thoughts?

**Comment by incertum** [comment]
@leogr and @LucaGuerra https://github.com/falcosecurity/libs/pull/1575#pullrequestreview-1785160993

**Comment by leogr** [comment]
@incertum 
I had lost track of this. What's missing?

**Comment by incertum** [comment]
I believe we improved a few things and in particular re-wrote the outputs formatting page https://falco.org/docs/outputs/formatting/.
