### ISSUE TITLE
small typo /kind area/documentation

### ISSUE THREAD

**Issue by kolbeface** [falcosecurity/falco-website#1193]
There is a small typo at the bottom of [this page ](https://falco.org/docs/reference/daemon/config-options/)
"Since Falco 0.30.0, this allows configuring ~~the~~ how the container orchestrator metadata is downloaded."

**Comment by kolbeface** [comment]
I found another typo/incompleteness under the rule descriptions found here, the rule "Redirect STDOUT/STDIN to Network Connection in Container" talks about tty != 0 first of all I feel like this acception benefited me greatly and could use a bump in visibility, this was highly applicable to be it silenced hundreds of thousands of false positives for my company and greatly simplified our rule acceptions.  I feel it should not be burried in a particular rule like it is, but also it is not complete.  The actual acception is "proc.tty != 0" which the only way i figured this out was by finding it burried in yet another  rule. Maybe more experienced devs simply know that it belongs to proc but its weird that in one rule you describe it in full and in another you abbreviate it to simply "tty != 0"

**Comment by kolbeface** [comment]
if documentation updating does not belong here where does it go?

**Comment by leogr** [comment]
> There is a small typo at the bottom of [this page ](https://falco.org/docs/reference/daemon/config-options/)
> "Since Falco 0.30.0, this allows configuring ~the~ how the container orchestrator metadata is downloaded."

That configuration node should be removed in Falco 0.37, thus fixing this.
/assign @LucaGuerra

**Comment by leogr** [comment]
> I found another typo/incompleteness under the rule descriptions found here, the rule "Redirect STDOUT/STDIN to Network Connection in Container" talks about tty != 0 first of all I feel like this acception benefited me greatly and could use a bump in visibility, this was highly applicable to be it silenced hundreds of thousands of false positives for my company and greatly simplified our rule acceptions. I feel it should not be burried in a particular rule like it is, but also it is not complete. The actual acception is "proc.tty != 0" which the only way i figured this out was by finding it burried in yet another rule. Maybe more experienced devs simply know that it belongs to proc but its weird that in one rule you describe it in full and in another you abbreviate it to simply "tty != 0"

Hey @kolbeface 

For rules, see https://github.com/falcosecurity/rules/blob/main/rules/falco_rules.yaml
If you find any typos, I recommend you to open a PR directly,.

**Comment by mikegcoleman** [comment]
@leogr so we don't need to fix this because the affected entry is going away in 0.37?

**Comment by leogr** [comment]
> @leogr so we don't need to fix this because the affected entry is going away in 0.37?

Yes.
