### ISSUE TITLE
Add banner to landing website for important updates and warnings

### ISSUE THREAD

**Issue by incertum** [falcosecurity/falco-website#1230]
I find banners on top of websites extremely helpful to communicate important updates. For example, it is a common practice to communicate planned outages or production freezes. That way we may increase our chances of setting expectations and avoid frustrations when upgrading Falco.

For the Falco 0.37.0 release it could highlight the following:

- Falco rules now follow semantic versioning and the most recent Falco rules release requires Falco >= 0.37.0
- Falco will deprecate the following configs xyz in Falco 0.38, start using the new config options today (most notably the new `engine` config) 
- The `-k` flag no longer exists. Instead, we've introduced a new opt-in `k8smeta` plugin, although it isn't necessary for most Falco use cases. This is because the familiar `k8s` fields are extracted from the container runtime socket concurrently while looking up container images.
- Check out the new Supported Fields 
- ...

or similar ...

**Comment by LucaGuerra** [comment]
Hey Melissa, this is now already in the website! We have used this to display a graduation banner for a month. We can use that banner to display any information we please.

**Comment by incertum** [comment]
Saw this, amazing! Thanks!
