### ISSUE TITLE
Document the new scalable k8s metadata collector

### ISSUE THREAD

**Issue by LucaGuerra** [falcosecurity/falco-website#1250]
/area documentation

**What would you like to be added**:

Starting from Falco 0.37.0 we are offering a new scalable approach to monitor k8s metadata; many users that have attempted to use the previous mechanism have experienced performance issues which we wish to resolve. However, adopters must be informed about how to opt in and configure it and which fields will be available once it is enabled. The helm chart greatly helps here.

See details here: https://github.com/falcosecurity/falco/issues/2973

**Comment by alacuku** [comment]
Here: https://github.com/falcosecurity/charts/tree/master/charts/falco#k8s-metacollector

falcosecurity/charts#601
