### ISSUE TITLE
Document the Falco gRPC API python client

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco-website#126]
/area documentation

**What would you like to be added**:

Recently, [Mattia](https://github.com/mmat11) created [a Python client for the Falco gRPC API](https://github.com/falcosecurity/client-py).

I'd like it to be documented also on Falco's website, in the same way the Go client is documented (see [here](https://falco.org/docs/grpc/client-go)).

**Why is this needed**:

We need to document everything in order to foster comprension, adoption, and contribution.

**Comment by leodido** [comment]
@mmat11 maybe do you want to document it?

**Comment by mmat11** [comment]
Sure!
