### ISSUE TITLE
"Copy" during Getting Started flow produces broken command due to indentation

### ISSUE THREAD

**Issue by jmolnar-comparative** [falcosecurity/falco-website#1310]
### Minor Problem in: Getting Started - Falco Linux Quickstart

Because of indentation:

```sh
    sudo bash -c 'cat << EOF > /etc/apt/sources.list.d/falcosecurity.list
    deb [signed-by=/usr/share/keyrings/falco-archive-keyring.gpg] https://download.falco.org/packages/deb stable main
    EOF'
# ^ indented here, but EOF must not be indented
```

one gets ``bash: line 3: warning: here-document at line 1 delimited by end-of-file (wanted `EOF')``

and the sources list does not get updated.

### Recommendation

That you don't indent code on this page.

### Source Link

https://github.com/falcosecurity/falco-website/blob/feac01ffb10756608cffbd6ea2513b3cb3bc0f0c/content/en/docs/getting-started/linux-quickstart.md?plain=1#L79-L83

**Comment by LucaGuerra** [comment]
Thank you for noticing this! I have opened a PR to fix it (and adding some syntax higlighting so it's less confusing) 🚀 . If you can, next time you notice something similar, could you please open a PR directly to fix it? We'll be grateful, approve it quickly and you'll also become a part of Falco ;)

**Comment by jmolnar-comparative** [comment]
> next time you notice something similar, could you please open a PR directly to fix it?

Sure thing; one just never knows how receptive a project is to random contributors, and I didn't want to waste time in case you guys were the "closed-off" kind of team
