### ISSUE TITLE
For consideration: Falco + YugabyteDB on GKE blog post

### ISSUE THREAD

**Issue by jguerreroyb** [falcosecurity/falco-website#132]
/area blog

**What would you like to be added**:

I've written a step-by-step blog post on how to integrate Falco with YugabyteDB running on GKE. See attached PDF. Happy to share out the source file with the appropriate folks.

**Why is this needed**:

YugabyteDB is a 100% open source, cloud-native database and we are looking to provide our users with as much information as possible on how to integrate YugabyteDB with CNCF projects...Falco being one of them.

[Getting Started with Falco and Cloud-Native Distributed SQL on Google Kubernetes Engine (1).pdf](https://github.com/falcosecurity/falco-website/files/4195610/Getting.Started.with.Falco.and.Cloud-Native.Distributed.SQL.on.Google.Kubernetes.Engine.1.pdf)

**Comment by Issif** [comment]
Hi,

That's a nice article, my only remark is that you have set a rule with that output :

```
output: "Login from user1 to YugabyteDB (connection=%fd.name)"
```

but this is not the rule that's triggered, as you can see in your log extract, this is not the pattern of your rule :

```
02:55:35.245247928: Error File below / or /root opened for writing (user=​root​ command=ysqlsh -U ​user1​ -h yb-tserver-0 -d yugabyte parent=bash file=/root/.psql_history program=ysqlsh container_id=ac8028a3c3bc image=yugabytedb/yugabyte) k8s.ns=yb-demo k8s.pod=yb-tserver-0 container=ac8028a3c3bc k8s.ns=yb-demo k8s.pod=yb-tserver-0 container=ac8028a3c3bc
```

**Comment by jguerreroyb** [comment]
@Issif - thanks for the pointer! (Bear with me, I am a Falco N00b!) 

Now I see that the rule that is getting triggered is in _/etc/falco/falco_rules.yaml_, specifically:

_rule: Write below root
desc: an attempt to write to any file directly below / or /root_

Thanks!

**Question No. 1**

If YugabyteDB has three APIs that by default listen on:

* YSQL - port 5433
* YCQL - port 9042
* YEDIS - port 6379

Would the following rules in _application_rules.yaml_ be valid if I want to make sure I track whenever someone connects to YugabyteDB as the superuser "yugabyte" on a non standard port?

```
# YugabyteDB ports
- macro: yugabytedb_ysql_port
  condition: fd.sport=5433
- macro: yugabytedb_ycql_port
  condition: fd.sport=9042
- macro: yugabytedb_yedis
  condition: fd.sport=6379
- macro: yugabytedb_port
  condition: yugabytedb_ysql_port or yugabytedb_ycql_port or yugabytedb_yedis

# - rule: YugabyteDB unexpected network inbound traffic
#   desc: inbound network traffic to YugabyteDB on a port other than the standard ports
#   condition: user.name = yugabyte and inbound and not yugabytedb_port
#   output: "Inbound network traffic to YugabyteDB on unexpected port (connection=%fd.name)"
#   priority: WARNING

# - rule: YugabyteDB unexpected network outbound traffic
#   desc: outbound network traffic from YugabyteDB on a port other than the standard ports
#   condition: user.name = yugabyte and outbound and not yugabytedb_port
#   output: "Outbound network traffic from YugabyteDB on unexpected port (connection=%fd.name)"
#   priority: WARNING
```
**Question No. 2**

How would  I create a rule that would audit logins by specific users on the normal ports, like I originally intended? ("yugabyte" is the superuser created by default.)

Would something like this work in  _application_rules.yaml_ ?

```
# - rule: Audit logins by superuser yugabyte to yugabytedb
#   desc: login by yugabyte superuser to yugabytedb on YSQL port
#   condition: user.name = yugabyte and inbound and yugabytedb_ysql_port
#   output: Inbound network traffic from yugabyte superuser to YugabyteDB on YSQLport (connection=%fd.name)"
#   priority: WARNING

**Comment by Issif** [comment]
Hi,

Be carefull, `user.name` is the system user than runs the action, it hasn't direct link with the db user who's used to connect on your database.

I don't know if it's possible to check that, as it's inside TCP packets.

Otherwise, your rule syntaxes seem good.
