### ISSUE TITLE
Broken links on Training section of the website

### ISSUE THREAD

**Issue by netops2devops** [falcosecurity/falco-website#1352]
**What is wrong with the website or needs to be cleaned?**

Hi folks, 

I noticed that the links to training content under **courtesy of Sysdig** on this page https://falco.org/training/ appear to be broken. I was able to access the content under those links just a few weeks ago but can no longer do so. Can those videos be made available again? 

Thank you for your contributions.

**Comment by Andreagit97** [comment]
thank you for reporting! cc @Issif

**Comment by GurdipS5** [comment]
Getting this too.

**Comment by LucaGuerra** [comment]
Fixed by https://github.com/falcosecurity/falco-website/pull/1353 :)
