### ISSUE TITLE
Replace deprecated cri options for Falco 0.39.0

### ISSUE THREAD

**Issue by ekoops** [falcosecurity/falco-website#1378]
/area documentation

**What would you like to be added**:

`--cri` and `--disable-cri-async` will be deprecated in `0.39.0` and will be removed in `0.40.0` as it is possible to see [here](https://github.com/falcosecurity/falco/pull/3329). Any reference to these options should be removed in favor of  the corresponding `-o container_engines.cri.<option>` alternative.

**Why is this needed**:

This is needed in order to align the documentation with the new upcoming falco version.

**Comment by vidhvath28** [comment]
@ekoops  I want to work on this documentation issue as a part of hackoctober 2024

**Comment by ekoops** [comment]
> @ekoops I want to work on this documentation issue as a part of hackoctober 2024

Nice! Please feel free to move ahead!

**Comment by ekoops** [comment]
Hi @vidhvath28 . Did you decide to work on it?
