### ISSUE TITLE
gRPC version service documentation 

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco-website#141]
/area documentation

**What would you like to be added**:

gRPC version service documentation.

The feature was added here https://github.com/falcosecurity/falco/pull/872

**Why is this needed**:
Once 0.20.0 is released users might want to use this feature but they have no way to know how besides reading the code.

We need something like this for the outputs: https://falco.org/docs/grpc/

**Comment by leodido** [comment]
/remove-lifecycle rotten
L.
