### ISSUE TITLE
Can't navigate documentation on Mobile

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco-website#146]
**What happened**:

As a user, while navigating the Falco Documentation on my mobile devices with less than 800px width I can't see the navigation.

This is preventing me to go through the pages and learn how to use Falco.

Vertical Example on a phone screen 320x480
![image](https://user-images.githubusercontent.com/3083633/75232767-0eac6700-57b8-11ea-946f-783d71767aab.png)

This is what I see if I click the menu icon top right, always on phone screen 320x480. It only shows the top level menus.
![image](https://user-images.githubusercontent.com/3083633/75232790-1a982900-57b8-11ea-9aa9-a13e7729258f.png)

Horizontal Example on a phone screen 320x480
![image](https://user-images.githubusercontent.com/3083633/75232739-06542c00-57b8-11ea-9c5c-3088923b9f17.png)
Horizontal Example on an iPad 768x1024
![image](https://user-images.githubusercontent.com/3083633/75232859-3a2f5180-57b8-11ea-8eb3-41a6a3c01603.png)

**What you expected to happen**:

I expect it to show me the menu, like in this figure. However it will need to be adapted for mobile devices.

![image](https://user-images.githubusercontent.com/3083633/75232889-46b3aa00-57b8-11ea-97bf-ae3ebed69c0f.png)

**How to reproduce it (as minimally and precisely as possible)**:

Go to https://falco.org/docs using a mobile device and see how you can't navigate the docs.

**Anything else we need to know?**:

**Comment by fntlnz** [comment]
Also, on mobile we have a traffic drop on `/docs` of 90% compared to the 50% of tablets (considering that tablets also might not have the docs menu)

Traffic on tablet and desktops
![image](https://user-images.githubusercontent.com/3083633/75248891-5beb0180-57d5-11ea-8988-48d494797b62.png)
![image](https://user-images.githubusercontent.com/3083633/75248963-8472fb80-57d5-11ea-8f2a-0df638b9a145.png)

Traffic on Mobile
![image](https://user-images.githubusercontent.com/3083633/75248928-6dcca480-57d5-11ea-95c4-96a5541b7191.png)

**Comment by skandix** [comment]
I think I know how to fix this, will take a look at it soon.
