### ISSUE TITLE
Inconsistency in Kubernetes Audit example

### ISSUE THREAD

**Issue by thecodejunkie** [falcosecurity/falco-website#159]
Hi,

I noticed that the [Kubernetes Audit example](https://github.com/falcosecurity/falco-website/blob/master/content/en/docs/event-sources/kubernetes-audit.md#example) defines the following `create` macro

```
- macro: create
  condition: ka.verb=create
```

Then a bit further down, in the breakdown section, it mentions

> 3. `modify`: Checks whether the value of verb is one of the following: `create`, `update`, `patch`.

Looks like the breakdown section was updated in https://github.com/falcosecurity/falco-website/pull/140 10-days ago so perhaps the macro definition was forgotten?

**Comment by leogr** [comment]
Fixed by #323
