### ISSUE TITLE
Add Korean Language Support in Documentation

### ISSUE THREAD

**Issue by onesolpark** [falcosecurity/falco-website#176]
/area documentation

**What would you like to be added**:
Add Korean as a supported language for falco documentations.

**Why is this needed**:
To help Korean users understand falco better.

**Comment by onesolpark** [comment]
I want to take initiative and kick off the Korean Doc translation.

**Comment by jmyung** [comment]
Hi @leodido @kris-nova 

For korean l10n, I have two questions.

- Would it be possible to make korean branch in this repo?
  * e.g. name of branch : `dev-0.21-ko.1`
  * This will work for managing outdated ko docs from upstream en docs.
- Could Some of korean contributer be maintainer?
  * reviewer : can review korean docs pr. They could fix wrong translation or typos in Korean.
  * approver : can approve korean docs pr and merge korean branch to master.

**Comment by leodido** [comment]
Hello @onesolpark,

please open a PR that creates `content/ko/docs` directory and initial skeleton for Korean docs.

In that directory, we can and we'll totally create a sub OWNER file containing korean docs contributors :)

**Comment by onesolpark** [comment]
I'll open a PR that holds the skeleton for Korean docs and an initial page asap 
(Tomorrow at the latest in KST time).
