### ISSUE TITLE
Document the two-step approach to run Falco with docker 

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco-website#186]
/area documentation

**What would you like to be added**:

A snippet showing how to install the Falco drivers via the Falco docker image in a two-step fashion. One, privileged, just to compile or download (from the Drivers Build Grid) and install the driver, and the second one to run Falco.

**Why is this needed**:

https://github.com/falcosecurity/falco/pull/1158

**Comment by leogr** [comment]
I believe this has been solved with:
- https://falco.org/docs/installation/#install-driver
- https://falco.org/docs/running/#docker-least-privileged
