### ISSUE TITLE
Update the website when a new Falco version has been released

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco-website#188]
**What is wrong with the website or needs to be cleaned?**

As commented [here](https://github.com/falcosecurity/falco/pull/1150#discussion_r413250329), we could avoid to manually update the website via Netlify each time we release a new Falco version.
How? TBD.

@leodido proposal:
> We could remove this step completely if we add a CI scheduled job (CircleCI or GH action?) to run the website build daily.

**Comment by lucperkins** [comment]
@leogr You can deploy the site by `POST`ing to a specific endpoint, so that's pretty easy. The trickier part is updating the version information and sha256 checksum in the site config. There aren't really any great options there.

**Comment by leogr** [comment]
Good point.

Btw, I still didn't understand completely how the automation works here - my fault, I haven't had enough time to dig into.

Anyway, I noticed something that seems inconsistent to me:
 - the [published docs](https://falco.org/docs/) are saying v0.22.1 (below the falco logo)
 - BUT the config has still v0.20.0 [here](https://github.com/falcosecurity/falco-website/blob/master/config.yaml#L264)

/cc @leodido

**Comment by leodido** [comment]
That is because, after the hotfix release of 0.22.1, I run a cache clean & build of the website via Netlify. But I have not sent a PR towards the website to update the config value.
