### ISSUE TITLE
GKE specific installation notes

### ISSUE THREAD

**Issue by nibalizer** [falcosecurity/falco-website#192]
/area documentation

**What would you like to be added**:

User mcjay on slack noted that when trying to configure k8s audit rules on GKE there are platform specific limitations. [This tool](https://github.com/codeonline-io/falco-gke-audit-bridge) has been written to deal with this. We should document this in the correct place.

I'm adding an issue here instead of just writing some blurbs because we're redoing all this anyway. (#184 

**Why is this needed**:

Better experience for our users.

Ref: #184

**Comment by jaychan-q** [comment]
The falco k8s audit rules dont work by default on EKS (AWS), AKS (Azure) and GKE (GCP) as per user tlabarussias in another slack message.

**Comment by jaychan-q** [comment]
Saw this tool for getting EKS audit logs to falco. https://github.com/xebia/falco-eks-audit-bridge
