### ISSUE TITLE
Invalid link : https://falco.org/docs/installation/#daemonset-manifests

### ISSUE THREAD

**Issue by nlamirault** [falcosecurity/falco-website#205]
According to the documentation : 
Clone the Falco repo and change to the directory with the manifests.

```
git clone https://github.com/falcosecurity/falco/
cd falco/integrations/k8s-using-daemonset
```

But directory only exists on tag. We must checkout tags and not the master branch.

**Comment by leogr** [comment]
I think this does not apply anymore since now the documentation does not point to manifests files.
/close
