### ISSUE TITLE
Front end feedback

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco-website#207]
1t  44 minutes ago
That looks real nice. i noticed what looks like a bug to me though. when i scroll down (in chrome) after freshly loading the page, the three boxes flicker for me.
QuickTime Movie 
falcoorg-bug.mov
1 MB QuickTime Movie— Click to download

capitangolo  38 minutes ago
I find the spacing in the logos section weird. Logos are too big or too smashed together. Looks like there is too much spacing after the section titles.
Some logos have white background, looks weird: League, Preferral, Logz.io, shujnko, grafana, Red Hat, StatsD
Some logos are cut by the borders: Kubernetes, OPA, Prometheus, Azure / CNCF at the bottom.
PD: Looks great! (edited) 
Screen Shot 2020-05-20 at 17.32.01.png 
Screen Shot 2020-05-20 at 17.32.01.png

ck:spiral_calendar_pad:  20 minutes ago
The CNCF logo also gets that corner cutting look -
image.png 
image.png

Janet:house_with_garden:  20 minutes ago
I like the reference to originally created by Sysdig. However, it is a bit large compared with the other elements. From a design standpoint we may be able to improve the visual appeal, particularly on the top half of the page. (edited) 

ck:spiral_calendar_pad:  19 minutes ago
Also I didn't get a GDPR style cookie check.

ck:spiral_calendar_pad:  19 minutes ago
But I love it! Looks really slick and professional. Awesome work!

ck:spiral_calendar_pad:  10 minutes ago
I also love how clean it looks on mobile too, great job!

benedetto:flag-lu:  5 minutes ago
the nav line at the top changes when going into doc - it would be nice if it was the same (edited)

**Comment by kris-nova** [comment]
Grzegorz Nosek:spiral_calendar_pad:  1 hour ago
the icons could use some spacing before the text (and maybe consistent width?)
other than that, :star-struck:
image.png 
image.png



davide  1 hour ago
nice!
15-sec viewer comments:
1) the top 3 boxes look clickable (I tried clicking the box and the title, couldn’t believe they were not sending me somewhere else)
2) icon-text spacing is a little too narrow, I’d give it few more pixels of air. Same goes for within logos as well
3) The first title is centered, the second is left-aligned. That seems a little off as well.

davide  41 minutes ago
Also, the initial spinner was kinda unexpected… you’d never really expect a “loading” step for a simple “marketing” web page like this. I’ve never seen spinners for anything besides proper web applications. Nice, just unexpected and potentially hiding bigger tech problems under the carpet.

**Comment by capitangolo** [comment]
Hi all,

I would like to fix a couple of tiny issues in the logos section that aren't addressed in @skandix PR -> https://github.com/falcosecurity/falco-website/pull/209

Have some questions:
1. Is there a guide / rules for PR's?
2. @skandix Are you working on more enhancements?
3. @kris-nova, anyone else… Shall I reopen this issue / create a new one to track these changes?

**Comment by skandix** [comment]
Just pushed the rest of the things I've done to my open PR.
