### ISSUE TITLE
Falco Alerts: an example logrotate config is a broken link

### ISSUE THREAD

**Issue by oke-py** [falcosecurity/falco-website#369]
**What is wrong with the website or needs to be cleaned?**

> If you'd like to use a program like logrotate to rotate the output file, an example logrotate config is available here.

"here" link is broken. https://github.com/falcosecurity/falco/blob/master/examples/logrotate/falco returns 404.

* https://falco.org/docs/alerts/#file-output
* https://falco.org/ja/docs/alerts/#%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%87%BA%E5%8A%9B

![broken-link](https://user-images.githubusercontent.com/4710215/105157283-2919cc80-5b50-11eb-97d3-935e7b013a1a.png)

**Comment by Rajakavitha1** [comment]
Thanks for pointing the issue @oke-py .

The correct link is: https://github.com/falcosecurity/falco/blob/ffd8747ec0943db2546c3270826e1700dc4df75f/examples/logrotate/falco
