### ISSUE TITLE
Tracking Portuguese Translation Progress (M1)

### ISSUE THREAD

**Issue by pasimoes** [falcosecurity/falco-website#396]
/area documentation

**What would you like to be added**:
Keep track of the translation of all documentation to Portuguese

**Why is this needed**:
To allow Portuguese speakers to have access to documentation and help the adoption of Falco.

**Comment by magnologan** [comment]
We are translating the Cloud Native Security white paper here: [Cloud Native Security White Paper Brazilian Portuguese Translation](https://github.com/cncf/sig-security/issues/509) 

So let me know if we can help in anything here as well. Cheers!

**Comment by pasimoes** [comment]
Hi Falco team, could you please add the tag `language/pt`? And approve/assign this issue to me and @magnologan?
