### ISSUE TITLE
Cheatsheet doc

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco-website#42]
This issue intends to propose the creation of a cheatsheet-style doc for Falco, following from [this tweet](https://twitter.com/lucperkins/status/1146124804900003845) by @lucperkins.

I think that the target of the cheatsheet have to be the Falco rules (conditions, rules macros, common rules that the community most asks).

**Comment by lucperkins** [comment]
@leodido I think the way to go here is:

1. I'll create a cheatsheet template that enables people to easily add cheatsheet items (all these items will be kept in a single YAML file)
2. I'll make the cheatsheet page a draft initially (and thus not viewable on the production site)
3. I'll ask you and other maintainers to submit items
4. When we've reached an adequate number of items, I'll remove the draft status of the page and push it to prod

**Comment by leodido** [comment]
Sounds a really good plan to me! 🎆

**Comment by lucperkins** [comment]
Closing this for now, as the scaffolding is in place.
