### ISSUE TITLE
Translate Falco docs into Simplified Chinese

### ISSUE THREAD

**Issue by leodido** [falcosecurity/falco-website#43]
After the @Kaizhe's talk about Falco at KubeCon China we started to think there is a need to have Falco documentation translated to Simplified Chinese.

/kind translation

**Comment by lucperkins** [comment]
@leodido Do you have any volunteers or know anyone who can help out? If there are people available to do the work I can make the necessary changes on the site.

**Comment by leodido** [comment]
During the past week Office Hours @markyjackson-taulia said he probably knows someone can help us!

Marky did you have the opportunity to contact this person? :)

**Comment by markyjackson-taulia** [comment]
> During the past week Office Hours @markyjackson-taulia said he probably knows someone that can help us!
> 
> Marky did you have the opportunity to contact this person? :)

Yes, I have someone joining during our next office hours. I will tag him in this issue once we introduce him during the meeting

**Comment by markyjackson-taulia** [comment]
The person I spoke with couldn't join due to other commitments. He will join the next office hours.

**Comment by leodido** [comment]
Okay. Waiting this person🤞

**Comment by markyjackson-taulia** [comment]
I have verified with the initial person if he can still make it and he has informed me he cannot. I do have another person in mind whom I have pinged

cc: @leodido

**Comment by fntlnz** [comment]
Update on this, we have the docs home page translated in Chinese https://falco.org/zh/docs

We are still missing all the docs sub-pages and falco.org/zh home page.

**Comment by smarkm** [comment]
Do we need to make a simple translation policy like who want to start a new page translation just take an issue under `kind/translation` and give the path of the page, so that contributors to know the page  under translating by other translators
