### ISSUE TITLE
the relevance of the sysctl net.core.bpf_jit_enable 

### ISSUE THREAD

**Issue by MattUebel** [falcosecurity/falco-website#494]
👋  I've found `net.core.bpf_jit_enable` to be critical to falco's performance when running as a daemonset in large k8s clusters.

I've been unable to find this documented anywhere, in the repo or the docs site.
![image](https://user-images.githubusercontent.com/1601728/131903295-e8274fed-032e-4e8e-86df-2b03c1767e27.png)

I came across this sysctl while reading into the sysdig [documentation](https://github.com/draios/sysdig/wiki/eBPF#container-mode-recommended)

More context in https://github.com/falcosecurity/falco/issues/1710

**Comment by lucklypse** [comment]
Since I was editing the docs for another issue I took a stab at writing the eBPF jit note. Reviews appreciated :)

**Comment by MattUebel** [comment]
nice standout red box, I like it! 
![image](https://user-images.githubusercontent.com/1601728/132856890-71343c4c-8216-4efd-bc80-9835bc3066af.png)
