### ISSUE TITLE
Blog on the falcosecurity org adopting the Falco sidekick

### ISSUE THREAD

**Issue by kris-nova** [falcosecurity/falco-website#63]
**What would you like to be added**:

A blog that talks about the falco sidekick joining the falcosecurity org.
We also want to describe what the falco sidekick can do.
We also want to talk about how we will use the new gRPC falcosecurity/falco#789 work with the new Go SDK falcosecurity/falco#785 with the falco sidekick

**Why is this needed**:

To share the many use cases of Falco

**Comment by fntlnz** [comment]
/area blog
/kind content
/close

Done in https://github.com/falcosecurity/falco-website/pull/70
