### ISSUE TITLE
how to get a new driver release?

### ISSUE THREAD

**Issue by dwgillies-bluescape** [falcosecurity/falco-website#662]
How do I get a new driver into falco?  It is failing with : 

* Trying to download a prebuilt falco module from https://download.falco.org/driver/17f5df52a7d9ed6bb12d3b1768460def8439936d/falco_amazonlinux2_5.4.201-111.359.amzn2.x86_64_1.ko

**Comment by jasondellaluce** [comment]
This driver seems to come from an older commit hash, did you try running the latest version of Falco? Since the last few Falco releases, we are supporting more kernel versions in our drivers.

**Comment by dwgillies-bluescape** [comment]
Nope, sorry, still no good.  We have a govcloud service and are forced by an amazon security advisory to use the very latest amazon linux driver, we recompiled roughly Aug 5th, and are now looking for : 

```
* Looking for a falco module locally (kernel 5.4.204-113.362.amzn2.x86_64)
* Trying to download a prebuilt falco module from https://download.falco.org/driver/2.0.0%2Bdriver/x86_64/falco_amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.ko
```

I just tried the falco:0.32.2 and falco:latest docker images, and the driver compilation has only advanced up to amazonlinux2_5.4.196:

<img width="900" alt="Screen Shot 2022-08-11 at 11 30 20 AM" src="https://user-images.githubusercontent.com/83255730/184214632-4f48bcea-b689-4ddd-9a4b-6ed173a5ce6b.png">

This is one of the first times we are forced to upgrade our kernel by a nessus scan / admazon security advisory.  If these advisories come out periodically, and falco is always a month or two behind on amazon linux, then we will have to look for something more up-to-date than falco to monitor our cluster, regrettably.

**Comment by dwgillies-bluescape** [comment]
> @dwgillies-bluescape: There is not a label identifying the kind of this issue. Please specify it either using `/kind <group>` or manually from the side menu.
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

@poiana I cannot edit the Issue label BTW.

**Comment by dwgillies-bluescape** [comment]
Hi, our code is working again, from the driver built at 10:57 GMT today.  THank you for helping us in this matter.

```
2022-08-12T10:57:23.000Z        3.8 MB         [falco_amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.ko](https://download.falco.org/driver/2.0.0%2Bdriver/x86_64/falco_amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.ko)
2022-08-12T10:57:22.000Z        4.7 MB         [falco_amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.o](https://download.falco.org/driver/2.0.0%2Bdriver/x86_64/falco_amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.o)
```

**Comment by jasondellaluce** [comment]
@dwgillies-bluescape great to hear you solved your issue. Can we close this?

For the future I think this kind of issue is more suitable for `falcosecurity/falco` or `falcosecurity/test-infra`. Also, we provide kernel driver builds in a best-effort way, and it's almost impossible to have a perfect build matrix with all the most up-to-date kernel flavor versions. `falcosecurity/kernel-crawler` from @FedeDP mitigates this a lot, but sometimes is not enough. If update kernel version very frequently, I would suggest building the drivers on your own. The community is happy to help if you need guidance on this.
