### ISSUE TITLE
Falco.org Blog 

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco-website#67]
**What would you like to be added**:

We want to have a blog for falco, to publish announcments, how-tos share ideas, and so on.

We have a couple of ideas on the execution of this:

1. A static blog with hugo
2. A medium publication

**Why is this needed**:

We already have articles for it!

- https://docs.google.com/document/d/1hSpSNnlrkW5Z_hEondp5dz8apA_Zd1EKmtV1Lq4J1Rk/edit?usp=sharing
- https://github.com/falcosecurity/falco/issues/792

**Comment by lucperkins** [comment]
Okay, we have a baseline implementation in place: https://falco.org/blog, complete with an RSS feed. Y'all can get going with writing posts now!
