### ISSUE TITLE
Netlify builds using the Xenial build image will fail after November 15, 2022

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco-website#680]
**What happened**:

![Screenshot from 2022-09-07 16-46-27](https://user-images.githubusercontent.com/3390997/188908188-4ed2f984-7231-4d11-9249-75ab32b20983.png)

Ref https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239

**What you expected to happen**:

We have to switch to another image soon. 

**Anything else we need to know?**:

@falcosecurity/core-maintainers anyone can help?

**Comment by Issif** [comment]
I checked and I don't have access to the settings on Netlify, and I didn't find a way to configure the builder image in the netlify.toml.

Source: https://answers.netlify.com/t/please-read-end-of-support-for-xenial-build-image-everything-you-need-to-know/68239/14

**Comment by nate-double-u** [comment]
Hi, I can help with this. 

I wanted to double check tho, @leogr it looks like you have access to the Netlify account. If not, please let me know.

**Comment by nate-double-u** [comment]
This has been updated & tested.

<img width="1245" alt="Screen Shot 2022-10-06 at 4 07 36 PM" src="https://user-images.githubusercontent.com/4453979/194434484-e1e32649-40f0-4a6e-b899-bd5d5b62cab2.png">

There is a Ruby version warning now, but the site still builds correctly that update can probably be dealt with in a follow up issue.

```
4:03:22 PM: ---------------------------------------------------------------------
WARNING: Your site had a deprecated version of Ruby pinned (2.3.6), which is incompatible with this
build image. This build image only supports 2.4.x and later. We changed it to 2.7.2.

To learn how to set a custom Ruby version, visit the following link:
https://docs.netlify.com/configure-builds/manage-dependencies/#ruby

If you set a custom Ruby version lower than 2.4.x, you will need to select a different build image (Ubuntu Xenial 16.04).
The current build image only supports 2.4.x and later. You can select a different build image at the following link:
https://app.netlify.com/sites/falcosecurity/settings/deploys#build-image-selection
---------------------------------------------------------------------
```

**Comment by nate-double-u** [comment]
I can't close this issue 😅

I would still like to confirm with you @leogr, it does appear that you've got access to the https://app.netlify.com/sites/falcosecurity team. If this isn't true, could you let me know, and I can invite you (please share your email address with me if this is the case--either here or in the CNCF slack)

**Comment by Andreagit97** [comment]
Ei @nate-double-u as far as I know @leogr is on vacation he will come back in the next few days :) BTW thank you very much for your effort!!

**Comment by nate-double-u** [comment]
Happy to help 😃
