### ISSUE TITLE
Blog post alignment

### ISSUE THREAD

**Issue by lucperkins** [falcosecurity/falco-website#72]
Centered text in long-form paragraphs is a big no-no from a readability standpoint. See [here](https://medium.com/@meetchopz/10-bad-typography-habits-that-scream-amateur-8bac07f9c041), [here](https://guppyfishweb.com/web-design/text-alignment-center/), and [here](https://uxmovement.com/content/why-you-should-never-center-align-paragraph-text/).

**Comment by fntlnz** [comment]
I personally don't like centered blog posts. We copied the existing format from the other blog. Should we reword the posts?
