### ISSUE TITLE
Link the client-go documentation

### ISSUE THREAD

**Issue by fntlnz** [falcosecurity/falco-website#78]
/area documentation

**What would you like to be added**:

The Falco go client https://github.com/falcosecurity/client-go
now has a documentation page at https://godoc.org/github.com/falcosecurity/client-go/pkg/client

I think that we want to link that in the main website when we document the gRPC feature.

We can wait
**Why is this needed**:

Because we want the world to use the go client!

Blocked by #77

**Comment by Rajakavitha1** [comment]
@fntlnz Please let me know if this issue can be marked as closed because the website https://falco.org/docs/grpc/client-go/ does have the link to https://godoc.org/github.com/falcosecurity/client-go/pkg/client
