### ISSUE TITLE
Translate grpc/grpc-config in Korean

### ISSUE THREAD

**Issue by Virusuki** [falcosecurity/falco-website#796]
/area documentation

**What would you like to be added**:

**Why is this needed**:
No translation with grpc/grpc-config in Korean

**Comments**
The security of Kubernetes in the cloud is essential.
Not only English, but also various language support is needed.
So, Falco Doc's technical documentation needs Korean.

Page to Update:
https://falco.org/docs/grpc/grpc-config/

**Comment by Virusuki** [comment]
Sorry. it's a PR mistake.

I'll leave a comment on the https://github.com/falcosecurity/falco-website/issues/796 issue.

**Comment by vjjmiras** [comment]
Thank you very much for contributing with the Korean translation.

I'm sure the Korean-speaking community will also appreciate your efforts, and I encourage you to continue submitting PRs with your contributions.

If you need any support, feel free to ping me/us on the Slack channel.
