### ISSUE TITLE
Falco Plugins Developers Guide

### ISSUE THREAD

**Issue by RichardoC** [falcosecurity/falco-website#801]
**What would you like to be added**:
Clear guidance on how to build falco plugins using Golang such that they have compatible glibc versions. Probably including exact docker images that can be used for building

**Why is this needed**:
Built a plugin using the example of <https://github.com/Issif/docker-plugin#build> and following the guidance in <https://falco.org/docs/plugins/developers-guide/> on Ubuntu 22.04, and found that I'm using too modern a version of glibc for the version in the falco container and got a very sad error message.

```console

$ nerdctl run --rm -it -v$(pwd):/example:ro  --entrypoint="/bin/bash" falcosecurity/falco -c '/usr/bin/falco -u  -c /example/falco.yaml  -r /falco_rules.yaml  --list-plugins'
Runtime error: cannot load plugin /example/libexample.so: can't load plugin dynamic library: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /example/libexample.so). Exiting.
Error: exit status 1
```

**Comment by Issif** [comment]
cc @jasondellaluce
