### ISSUE TITLE
Add "About" Section on Falco website

### ISSUE THREAD

**Issue by aijamalnk** [falcosecurity/falco-website#817]
/area documentation

**What would you like to be added**:

A section in the website (falco.org) called About. In this section we should present a gentle introduction to runtime security and Falco in general.

The About section should address several questions that a prospective user might have about Falco. For example:

- What is Falco?
- What are the main use cases of Falco?
- Why do we need runtime security tooling?
- Other frequently asked questions

**Why is this needed**:

A gentle, use-case-driven introduction to Falco will help prospective Falco users understand the capabilities, benefits and main features of Falco before digging into the documentation and its technical characteristics.

**Subtasks**

- #820 
- #821 
- #822

**Comment by aijamalnk** [comment]
Hi all,

Below is the proposed design for "About" page on falco.org.

- This page has a new styling that we will continue to apply to the rest of the site. 
- The purpose of this page is to introduce User to the high level concept in Falco and its components like "Falco Sidekick"
- This page also highlights/refers to other important existing content (docs, blogs, GH repos) and easy to navigate
- This page provides multiple graphs to enhance user's understanding of complex concepts in Falco
- This page includes breadcrumbs to other pieces of content that is good to read after completing this page


The PDF has notes/annotations with extra explanation for clarity. The current text uses some placeholder texts that will be fixed when we create a PR.


[ABOUT (2).pdf](https://github.com/falcosecurity/falco-website/files/10800328/ABOUT.2.pdf)

**Comment by Andreagit97** [comment]
> This page provides multiple graphs to enhance user's understanding of complex concepts in Falco

I love it :heart:

**Comment by aijamalnk** [comment]
As we were working on the content for "About" page, we realized we want to provide more complete story about Falco and reasons to adopt Falco and Falco use cases without making the page overwhelmingly long. Therefore, we decided to split out certain topics into separate pages. Specifically:
- Why Falco
- Falco use cases
These pages will all live under "About" section and are tracked as separate issues:

#https://github.com/falcosecurity/falco-website/issues/846
#https://github.com/falcosecurity/falco-website/issues/847

**Comment by aijamalnk** [comment]
Closing this issue as it is complete: https://github.com/falcosecurity/falco-website/pull/837
