### ISSUE TITLE
https://falco.org/docs/grpc/#certificates is supposed to tell how to generate certs but its not showing

### ISSUE THREAD

**Issue by jitendrazkumar** [falcosecurity/falco-website#834]
https://falco.org/docs/grpc/#certificates is supposed to tell how to generate certs but its not showing

**Comment by vjjmiras** [comment]
Hey @jitendrazkumar, that snippet of documentation was moved to another page in December 2022. The content is now a link deeper: https://falco.org/docs/grpc/grpc-config/#certificates.

Could you share where you have found the link to correct it?

**Comment by vjjmiras** [comment]
I identified the [blog post](https://falco.org/blog/falco-kind-prometheus-grafana/) had the incorrect link. If there isn't any other page with the same issue, the PR #941 should fix this issue.
