### ISSUE TITLE
Ensure page feedback works under GA4

### ISSUE THREAD

**Issue by chalin** [falcosecurity/falco-website#974]
It seems that the Falco website has custom page-feedback code. That code will need to be updated to work with GA4.

---

### Old description

(The following old issue text isn't relevant. Keeping it for reference.)
 
If you'd like to make it easy to see page-feedback events under GA4, you'll need to setup an event-modificaiton rule. For details, see:

- https://github.com/google/docsy/issues/1302#issuecomment-1301550895

You can also track that issue for the status of a proper fix in Docsy.

/cc @caniszczyk @nate-double-u

/kind cleanup

**Comment by aijamalnk** [comment]
@chalin we do want to have the page-feedback events after the migration. Could you please help us to set up the event-modification rule? Thank you!

**Comment by chalin** [comment]
I've created the necessary event-modificaiton rule:

> <img width="950" alt="image" src="https://github.com/falcosecurity/falco-website/assets/4140793/401d2c2d-04ad-430a-8a65-28cc9204d6a4">

But it isn't processing events. I'll investigate shortly.

**Comment by chalin** [comment]
After deleting the previously added event-modification rule, I've confirmed (using https://tagassistant.google.com), that `page_helpful ` events are being received by the CNCF GA4 data stream:

> <img width="592" alt="Screen Shot 2023-06-13 at 16 20 30" src="https://github.com/falcosecurity/falco-website/assets/4140793/9acb9a24-9255-446c-892d-0d897c066d8e">

### Details

G-D5DEHT7DJ1

Page Location | dl | https://falco.org/about/
-- | -- | --
... | ... | ...
Page Referrer | dr | https://falco.org/
Page Title | dt | What is Falco? \| Falco
Event Name | en | page_helpful
System Property | _ee | 1
Event Parameter | ep.event_category | Helpful
Event Parameter | ep.event_label | /about/
Numeric Event Parameter | epn.value | 1
