### ISSUE TITLE
Delete non-CNCF GA4 property

### ISSUE THREAD

**Issue by chalin** [falcosecurity/falco-website#982]
- The [Sysdig GA4 property 345412682](https://analytics.google.com/analytics/web/#/p345412682) of data channel `G-EN7HNEVL6X` was created in December 2022, but hasn't been processing events properly.
- In the [#falco-docs](https://cloud-native.slack.com/archives/C059LP08UJY) channel (2023/05/31), @aijamalnk gave a thumbs up to scheduling that non-functional GA4 property for deletion. I'll track progress via this issue.

Tasks:

- [x] Schedule [Sysdig GA4 property 345412682](https://analytics.google.com/analytics/web/#/p345412682) for deletion - done 2023-11/14
- [ ] Confirm deletion on or after Dec 19, 2023

/assign @chalin

**Comment by chalin** [comment]
FYI, at the moment, Google is preventing us from deleting the Sysdig GA4 ID because it is connected to the UA ID. And Google is preventing us from disconnecting them.

**Comment by chalin** [comment]
Google still isn’t allowing us to delete those site IDs as of the time of writing. I suggest that we check again after the July UA-to-GA4 migration deadline.

**Comment by vjjmiras** [comment]
@chalin, just to follow up on the topic, are there any updates in this regard? Anything I could do to help?

**Comment by chalin** [comment]
@aijamalnk - I've checked again (10/18) and I still don't have permissions to unlink the unwanted properties nor to delete them 🤷🏼‍♂️

**Comment by chalin** [comment]
With help from Google, we've been able (we hope) to shed some light on the situation: only someone with admin access to the **Sysdig Google Analytics org** will be able to unlink the broken GA4 property from the now obsolete UA property. While I have admin access to both properties I don't have admin access to the Sysdig org.

> @chalin, just to follow up on the topic, are there any updates in this regard? Anything I could do to help?

@vjjmiras @aijamalnk yes! Can someone with Sysdig-org admin access unlink the properties and then I can do the rest of the cleanup. Or if you grant me access, I can unlink the properties.

**Comment by chalin** [comment]
The Sysdig UA and (broken) GA4 properties were disconnected today \o/. So I was able to **scheduled** the broken GA4 property **for deletion**:

> <img width="915" alt="sysdig-ga4-del" src="https://github.com/falcosecurity/falco-website/assets/4140793/e20df906-bf68-4d23-91f4-1e395846c7fc">

The property will be deleted on Dec 19, 2023.

As @aijamalnk and I noted today:

- The [UA property](https://analytics.google.com/analytics/web/?pli=1#/report/content-pages/a40398182w185781754p182920300/_u.date00=20230901&_u.date01=20231113&explorer-graphOptions.selected=analytics.nthDay) stopped collecting data on Oct 5, 2023.
- The new CNCF GA4 property is successfully collecting analytics.

**Comment by chalin** [comment]
I confirm that the broken GA4 property has been deleted. Closing.

> <img width="708" alt="image" src="https://github.com/falcosecurity/falco-website/assets/4140793/80ec36dd-f83a-454d-b70c-cb61625f5247">
